algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

A:inteiro

inicio

escreva("Informe um número: ")
leia(A)
se ((A%4=0) e (A%5=0)) entao
    escreva("O valor ",A," é divisível por 4 e 5.")
senao
    escreva("O valor ",A," NÃO é divisível por 4 e 5.")
fimse

fimalgoritmo